CREATE TABLE JUN28_LOGIN_BOARD(
	j_ID VARCHAR2(20 CHAR) NOT NULL,
	j_IMG VARCHAR2(200 CHAR) NOT NULL,
	DOI VARCHAR2(200 CHAR) NOT NULL,
	CONTENT VARCHAR2(300 CHAR) NOT NULL,
	POSTNUM NUMBER NOT NULL,
	CONSTRAINT PK_JUN28_LOGIN_BOARD PRIMARY KEY(POSTNUM)
);

DROP TABLE JUN28_LOGIN_BOARD;

truncate table JUN28_LOGIN_BOARD;

INSERT INTO JUN28_LOGIN_BOARD VALUES('TEST','TEST','YYYYMMDDHHMM','TEST TEST TEST');

SELECT * FROM JUN28_LOGIN_BOARD;

SELECT * FROM (SELECT ROWNUM AS RN, j_ID, j_IMG, doi, content, PostNum FROM JUN28_LOGIN_BOARD ORDER BY POSTNUM) WHERE RN BETWEEN 1 AND 4;


--SELECT * FROM TAB;
--PURGE RECYCLEBIN;