-- 사과 테이블 : 생산지 / 색 / 맛 / 가격 / 사과 소개문
--만들고 데이터 2개정도

CREATE TABLE JUN26_APPLE(
	a_ORIGIN VARCHAR2(20 CHAR) NOT NULL,
	a_COLOR VARCHAR2(20 CHAR) NOT NULL,
	a_TASTE VARCHAR2(10 CHAR) NOT NULL,
	a_PRICE NUMBER(10) NOT NULL,
	a_INTRODUCE VARCHAR2(50 CHAR) NOT NULL,
	CONSTRAINT PK_APPLE PRIMARY KEY(a_ORIGIN)
);

--DROP TABLE JUN26_APPLE;

--truncate table JUN26_APPLE;

INSERT INTO JUN26_APPLE VALUES('금산','초록','새콤',2000,'맛있는 사과');
INSERT INTO JUN26_APPLE VALUES('밀양','빨강','달콤',3000,'얼음 사과');
INSERT INTO JUN26_APPLE VALUES('충주','초록/빨강','새콤달콤',4000,'충주 사과');

SELECT * FROM JUN26_APPLE;

--SELECT * FROM TAB;
--PURGE RECYCLEBIN;